<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>reka</string>
	</array>
	<key>name</key>
	<string>Reka Configuration</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#body</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>arrayBody</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#leadingSpace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arrayInvalid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rekaAt</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arrayEntry</string>
				</dict>
			</array>
		</dict>
		<key>arrayBodyInComment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#leadingSpace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#invalid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arrayEntryInComment</string>
				</dict>
			</array>
		</dict>
		<key>arrayEntry</key>
		<dict>
			<key>begin</key>
			<string></string>
			<key>end</key>
			<string></string>
			<key>name</key>
			<string>arrayEntry.reka</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#doc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nested</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nestedArray</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rekaAt</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#val</string>
				</dict>
			</array>
		</dict>
		<key>arrayEntryInComment</key>
		<dict>
			<key>begin</key>
			<string></string>
			<key>end</key>
			<string></string>
			<key>name</key>
			<string>comment.reka</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#docInComment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nestedInComment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nestedArrayInComment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#valInComment</string>
				</dict>
			</array>
		</dict>
		<key>arrayInvalid</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>invalid.reka</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\])\s*</string>
		</dict>
		<key>body</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#leadingSpace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#invalid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rekaAt</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entry</string>
				</dict>
			</array>
		</dict>
		<key>bodyInComment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#leadingSpace</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#invalid</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#entryInComment</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>\/\/</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.entity.reka</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#docInComment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nestedInComment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nestedArrayInComment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#valInComment</string>
				</dict>
			</array>
		</dict>
		<key>doc</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#docHTML</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#docCSS</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#docJade</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#docXML</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#docJS</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#docSQL</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#docRuby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#docShell</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#docClojure</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#docOther</string>
				</dict>
			</array>
		</dict>
		<key>docCSS</key>
		<dict>
			<key>begin</key>
			<string>\s*&lt;&lt;\-\s+(text\/css|css)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.reka</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.css.embedded.reka</string>
			<key>end</key>
			<string>^\s*\-\-\-\-*\s*$</string>
			<key>name</key>
			<string>punctuation.reka</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<key>docClojure</key>
		<dict>
			<key>begin</key>
			<string>\s*&lt;&lt;\-\s+(clojure|clj)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.reka</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.clojure.embedded.reka</string>
			<key>end</key>
			<string>^\s*\-\-\-\-*\s*$</string>
			<key>name</key>
			<string>punctuation.reka</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.clojure</string>
				</dict>
			</array>
		</dict>
		<key>docHTML</key>
		<dict>
			<key>begin</key>
			<string>\s*&lt;&lt;\-\s+(text\/html|html)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.reka</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.html.embedded.reka</string>
			<key>end</key>
			<string>^\s*\-\-\-\-*\s*$</string>
			<key>name</key>
			<string>punctuation.reka</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<key>docInComment</key>
		<dict>
			<key>begin</key>
			<string>\s*&lt;&lt;\-\s+\S+?\s*$</string>
			<key>contentName</key>
			<string>comment.reka</string>
			<key>end</key>
			<string>^\s*\-\-\-\-*\s*$</string>
			<key>name</key>
			<string>comment.reka</string>
		</dict>
		<key>docJS</key>
		<dict>
			<key>begin</key>
			<string>\s*&lt;&lt;\-\s+(text\/javascript|application\/javascript|javascript|js)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.reka</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.js.embedded.reka</string>
			<key>end</key>
			<string>^\s*\-\-\-\-*\s*$</string>
			<key>name</key>
			<string>punctuation.reka</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>docJade</key>
		<dict>
			<key>begin</key>
			<string>\s*&lt;&lt;\-\s+(text\/jade|jade)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.reka</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.jade.embedded.reka</string>
			<key>end</key>
			<string>^\s*\-\-\-\-*\s*$</string>
			<key>name</key>
			<string>punctuation.reka</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.jade</string>
				</dict>
			</array>
		</dict>
		<key>docOther</key>
		<dict>
			<key>begin</key>
			<string>\s*&lt;&lt;\-\s+(\S+)?\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>unknown.reka</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>string.unknown.reka</string>
			<key>end</key>
			<string>^\s*\-\-\-\-*\s*$</string>
			<key>name</key>
			<string>punctuation.reka</string>
		</dict>
		<key>docRuby</key>
		<dict>
			<key>begin</key>
			<string>\s*&lt;&lt;\-\s+(text\/ruby|ruby|rb|gemfile)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.reka</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.ruby.embedded.reka</string>
			<key>end</key>
			<string>^\s*\-\-\-\-*\s*$</string>
			<key>name</key>
			<string>punctuation.reka</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby</string>
				</dict>
			</array>
		</dict>
		<key>docSQL</key>
		<dict>
			<key>begin</key>
			<string>\s*&lt;&lt;\-\s+(sql)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.reka</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.sql.embedded.reka</string>
			<key>end</key>
			<string>^\s*\-\-\-\-*\s*$</string>
			<key>name</key>
			<string>punctuation.reka</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.sql</string>
				</dict>
			</array>
		</dict>
		<key>docShell</key>
		<dict>
			<key>begin</key>
			<string>\s*&lt;&lt;\-\s+(bash)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.reka</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.shell.embedded.reka</string>
			<key>end</key>
			<string>^\s*\-\-\-\-*\s*$</string>
			<key>name</key>
			<string>punctuation.reka</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.shell</string>
				</dict>
			</array>
		</dict>
		<key>docXML</key>
		<dict>
			<key>begin</key>
			<string>\s*&lt;&lt;\-\s+(text\/xml|application\/xml|xml)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.reka</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>source.xml.embedded.reka</string>
			<key>end</key>
			<string>^\s*\-\-\-\-*\s*$</string>
			<key>name</key>
			<string>punctuation.reka</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.xml</string>
				</dict>
			</array>
		</dict>
		<key>entry</key>
		<dict>
			<key>begin</key>
			<string>(\/)?([^\s\/]+)(?:(\/)([^\s\/]+))?(?:(\/)([^\s\/]+))?(?:(\/)([^\s\/]+))?\s?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>punctuation</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>punctuation</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>entry.reka</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#doc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nested</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nestedArray</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#rekaAt</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#val</string>
				</dict>
			</array>
		</dict>
		<key>entryInComment</key>
		<dict>
			<key>begin</key>
			<string>\S+\s?</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.reka</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#docInComment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nestedInComment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nestedArrayInComment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#valInComment</string>
				</dict>
			</array>
		</dict>
		<key>invalid</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>invalid.reka</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\})\s*</string>
		</dict>
		<key>leadingSpace</key>
		<dict>
			<key>match</key>
			<string>^\s*</string>
		</dict>
		<key>nested</key>
		<dict>
			<key>begin</key>
			<string>(\{)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.reka</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^\s*(\})\s*$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.reka</string>
				</dict>
			</dict>
			<key>name</key>
			<string>nested.reka</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#body</string>
				</dict>
			</array>
		</dict>
		<key>nestedArray</key>
		<dict>
			<key>begin</key>
			<string>(\[)\s*$</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.reka</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^\s*(\])\s*$</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.reka</string>
				</dict>
			</dict>
			<key>name</key>
			<string>nestedArray.reka</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#arrayBody</string>
				</dict>
			</array>
		</dict>
		<key>nestedArrayInComment</key>
		<dict>
			<key>begin</key>
			<string>\[\s*$</string>
			<key>end</key>
			<string>^\s*\]\s*$</string>
			<key>name</key>
			<string>comment.reka</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#arrayBodyInComment</string>
				</dict>
			</array>
		</dict>
		<key>nestedInComment</key>
		<dict>
			<key>begin</key>
			<string>\{\s*$</string>
			<key>end</key>
			<string>^\s*\}\s*$</string>
			<key>name</key>
			<string>comment.reka</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#bodyInComment</string>
				</dict>
			</array>
		</dict>
		<key>rekaAt</key>
		<dict>
			<key>begin</key>
			<string>(@)([a-zA-Z0-9\-_]+)(?:(\()([^\)]*)(\)))?\s?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.constant.reka</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.constant.reka</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.constant.reka</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.constant.reka</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>at.reka</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#doc</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nested</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#nestedArray</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#val</string>
				</dict>
			</array>
		</dict>
		<key>val</key>
		<dict>
			<key>match</key>
			<string>.</string>
			<key>name</key>
			<string>string.quoted.double.val.reka</string>
		</dict>
		<key>valInComment</key>
		<dict>
			<key>match</key>
			<string>.</string>
			<key>name</key>
			<string>comment.reka</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.reka</string>
	<key>uuid</key>
	<string>63136c97-f2b8-45f6-ac13-b54271beb28c</string>
</dict>
</plist>
